import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedSecurity {
  final List<SecurityModel> results;

  AutogeneratedSecurity({this.results});

  factory AutogeneratedSecurity.fromJson(Map<String, dynamic> json) {
    List<SecurityModel> temp;
    if (json['results'] != null) {
      temp = <SecurityModel>[];
      json['results'].forEach((v) {
        temp.add(SecurityModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedSecurity(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SecurityModel extends Equatable {
  final int id;
  final String name;

  SecurityModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory SecurityModel.fromJson(Map<String, dynamic> json) {
    return SecurityModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
