import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedThought {
  final List<ThoughtModel> results;

  AutogeneratedThought({this.results});

  factory AutogeneratedThought.fromJson(Map<String, dynamic> json) {
    List<ThoughtModel> temp;
    if (json['results'] != null) {
      temp = <ThoughtModel>[];
      json['results'].forEach((v) {
        temp.add(ThoughtModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedThought(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ThoughtModel extends Equatable {
  final int id;
  final String name;

  ThoughtModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ThoughtModel.fromJson(Map<String, dynamic> json) {
    return ThoughtModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
