import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedThought {
  final List<ThoughtModel> results;

  AutogeneratedThought({this.results});

  factory AutogeneratedThought.fromJson(Map<String, dynamic> json) {
    List<ThoughtModel> temp;
    if (json['results'] != null) {
      temp = <ThoughtModel>[];
      json['results'].forEach((v) {
        temp.add(ThoughtModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedThought(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ThoughtModel extends Equatable {
  final String fromUserId;
  final String toUserId;
  final String thoughtOptionCode;
  final DateTime createdDate;

  ThoughtModel(
      this.fromUserId, this.toUserId, this.thoughtOptionCode, this.createdDate);

  @override
  List<Object> get props =>
      [fromUserId, toUserId, thoughtOptionCode, createdDate];

  factory ThoughtModel.fromJson(Map<String, dynamic> json) {
    return ThoughtModel(
        json['fromUserId'] as String,
        json['toUserId'] as String,
        json['thoughtOptionCode'] as String,
       
        json['createdDate'].toDate() as DateTime);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fromUserId'] = this.fromUserId;
    data['toUserId'] = this.toUserId;
    data['thoughtOptionCode'] = this.thoughtOptionCode;
    data['createdDate'] = this.createdDate;
    return data;
  }
}
